(function(){function t(c,b,a){"addEventListener"in window?c.addEventListener(b,a,!1):"attachEvent"in window&&c.attachEvent("on"+b,a)}function v(c){var b="Host page";window.top!==window.self&&(b=window.parentIFrame?window.parentIFrame.getId():"Nested host page");return"[iFrameSizer]["+b+"]"+c}function e(c){p&&"object"===typeof window.console&&console.log(v(c))}function x(c){"object"===typeof window.console&&console.warn(v(c))}function z(){null===f&&(f={x:void 0!==window.pageXOffset?window.pageXOffset:
document.documentElement.scrollLeft,y:void 0!==window.pageYOffset?window.pageYOffset:document.documentElement.scrollTop},e(" Get page position: "+f.x+","+f.y))}function y(){null!==f&&(G(f.x,f.y),e(" Set page position: "+f.x+","+f.y),f=null)}function G(c,b,a,d){function e(){k+=1/60;var a=k/p,l=n[d](a);1>a?(requestAnimFrame(e),window.scrollTo(f+(c-f)*l,h+(b-h)*l)):window.scrollTo(c,b)}var f=window.scrollX,h=window.scrollY;c=c||0;b=b||0;d=d||"easeOutSine";var k=0,p=Math.max(.1,Math.min(Math.max(Math.abs(h-
b),Math.abs(f-c))/(a||2E3),.8)),n={easeOutSine:function(a){return Math.sin(Math.PI/2*a)},easeInOutSine:function(a){return-.5*(Math.cos(Math.PI*a)-1)},easeInOutQuint:function(a){return 1>(a/=.5)?.5*Math.pow(a,5):.5*(Math.pow(a-2,5)+2)}};e()}function B(c){e(" Size reset requested by "+("init"===c.type?"host page":"iFrame"));z();C(function(){D(c);n("reset","reset",c.iframe,c.id)},c,"init")}function D(c){function b(b){c.iframe.style[b]=c[b]+"px";e(" IFrame ("+a+") "+b+" set to "+c[b]+"px")}var a=c.iframe.id;
d[a].sizeHeight&&b("height");d[a].sizeWidth&&b("width")}function C(c,b,a){a!==b.type&&h?(e(" Requesting animation frame"),h(c)):c()}function n(c,b,a,A){a&&a.contentWindow?(e("["+c+"] Sending msg to iframe ("+b+")"),a.contentWindow.postMessage("[iFrameSizer]"+b,"*")):(x("["+c+"] IFrame not found"),d[A]&&delete d[A])}function k(c,b,a){Infinity!==d[b][a]&&0!==d[b][a]&&(c.style[a]=d[b][a]+"px",e(" Set "+a+" = "+d[b][a]+"px"))}function E(c){var b=this,a=function(a){""===a&&(b.id=a="iFrameResizer"+H++,
p=(c||{}).log,e(" Added missing iframe ID: "+a+" ("+b.src+")"));return a}(b.id);(function(b){b=b||{};d[a]={};if("object"!==typeof b)throw new TypeError("Options is not an object.");for(var c in u)u.hasOwnProperty(c)&&(d[a][c]=b.hasOwnProperty(c)?b[c]:u[c]);p=d[a].log})(c);e(" IFrame scrolling "+(d[a].scrolling?"enabled":"disabled")+" for "+a);b.style.overflow=!1===d[a].scrolling?"hidden":"auto";b.scrolling=!1===d[a].scrolling?"no":"yes";k(b,a,"maxHeight");k(b,a,"minHeight");k(b,a,"maxWidth");k(b,
a,"minWidth");if("number"===typeof d[a].bodyMargin||"0"===d[a].bodyMargin)d[a].bodyMarginV1=d[a].bodyMargin,d[a].bodyMargin=""+d[a].bodyMargin+"px";(function(c){t(b,"load",function(){var e=F;n("iFrame.onload",c,b);!e&&d[a].heightCalculationMethod in I&&B({iframe:b,height:0,width:0,type:"init"})});n("init",c,b)})(a+":"+d[a].bodyMarginV1+":"+d[a].sizeWidth+":"+d[a].log+":"+d[a].interval+":"+d[a].enablePublicMethods+":"+d[a].autoResize+":"+d[a].bodyMargin+":"+d[a].heightCalculationMethod+":"+d[a].bodyBackground+
":"+d[a].bodyPadding+":"+d[a].tolerance+":"+d[a].enableInPageLinks+":"+d[a].resizeFrom)}function J(c,b){null===q&&(q=setTimeout(function(){q=null;c()},b))}function r(){function c(b,a){if(b.tagName){if("IFRAME"!==b.tagName.toUpperCase())throw new TypeError("Expected <IFRAME> tag, found <"+b.tagName+">.");E.call(b,a)}else throw new TypeError("Object is not a valid DOM element");}return function(b,a){switch(typeof a){case "undefined":case "string":Array.prototype.forEach.call(document.querySelectorAll(a||
"iframe"),function(a){c(a,b)});break;case "object":c(a,b);break;default:throw new TypeError("Unexpected data type ("+typeof a+").");}}}function K(c){c.fn.iFrameResize=function(b){return this.filter("iframe").each(function(a,c){E.call(c,b)}).end()}}var H=0,F=!0,p=!1,f=null,h=window.requestAnimationFrame,I={max:1,scroll:1,bodyScroll:1,documentElementScroll:1},d={},q=null,u={autoResize:!0,bodyBackground:null,bodyMargin:null,bodyMarginV1:8,bodyPadding:null,checkOrigin:!0,enableInPageLinks:!1,enablePublicMethods:!1,
heightCalculationMethod:"offset",interval:32,log:!1,maxHeight:Infinity,maxWidth:Infinity,minHeight:0,minWidth:0,resizeFrom:"parent",scrolling:!1,sizeHeight:!0,sizeWidth:!1,tolerance:0,closedCallback:function(){},initCallback:function(){},messageCallback:function(){},resizedCallback:function(){},scrollCallback:function(){return!0},minHeightCallBack:function(){return this.minHeight}};(function(){var c=["moz","webkit","o","ms"],b;for(b=0;b<c.length&&!h;b+=1)h=window[c[b]+"RequestAnimationFrame"];h||
e(" RequestAnimationFrame not supported")})();t(window,"message",function(c){function b(){k("Height");k("Width");C(function(){D(g);y();d[m].resizedCallback(g)},g,"resetPage")}function a(a){var b=a.id;e(" Removing iFrame: "+b);a.parentNode.removeChild(a);d[b].closedCallback(b);delete d[b];e(" --")}function h(){var a=l.substr(13).split(":");return{iframe:document.getElementById(a[0]),id:a[0],height:a[1],width:a[2],type:a[3]}}function k(a){var b=Number(d[m]["max"+a]),c=Number(d[m]["min"+a]),f=a.toLowerCase(),
h=Number(g[f]);if(c>b)throw Error("Value for min"+a+" can not be greater than max"+a);e(" Checking "+f+" is in range "+c+"-"+b);h<c&&(h=c,e(" Set "+f+" to min value"));h>b&&(h=b,e(" Set "+f+" to max value"));g[f]=""+h}function n(){var a=c.origin,b=g.iframe.src.split("/").slice(0,3).join("/");if(d[m].checkOrigin&&(e(" Checking connection is from: "+b),"null"!==""+a&&a!==b))throw Error("Unexpected message received from: "+a+" for "+g.iframe.id+". Message was: "+c.data+". This error can be disabled by adding the checkOrigin: false option.");
return!0}function t(){var a=g.type in{"true":1,"false":1};a&&e(" Ignoring init message from meta parent page");return a}function u(a){e(" MessageCallback passed: {iframe: "+g.iframe.id+", message: "+a+"}");d[m].messageCallback({iframe:g.iframe,message:JSON.parse(a)});e(" --")}function q(a){a=a.getBoundingClientRect();z();return{x:parseInt(a.left,10)+parseInt(f.x,10),y:parseInt(a.top,10)+parseInt(f.y,10)}}function r(a){var b=a?q(g.iframe):{x:0,y:0},c={x:Number(g.width)+b.x,y:Number(g.height)+b.y};
e(" Reposition requested from iFrame (offset x:"+b.x+" y:"+b.y+")");window.top!==window.self?window.parentIFrame?a?parentIFrame.scrollToOffset(c.x,c.y):parentIFrame.scrollTo(g.width,g.height):x(" Unable to scroll to requested position, window.parentIFrame not found"):(f=c,!1!==d[m].scrollCallback(f)&&y(),e(" --"))}function v(a){a=a.split("#")[1]||"";var b=decodeURIComponent(a),b=document.getElementById(b)||document.getElementsByName(b)[0];window.top!==window.self?window.parentIFrame?parentIFrame.moveToAnchor(a):
e(" In page link #"+a+" not found and window.parentIFrame not found"):b?(b=q(b),e(" Moving to in page link (#"+a+") at x: "+b.x+" y: "+b.y),f={x:b.x,y:b.y},!1!==d[m].scrollCallback(f)&&y(),e(" --")):e(" In page link #"+a+" not found")}var l=c.data,g={},m=null;if("[iFrameSizer]"===(""+l).substr(0,13)){g=h();m=g.id;p=d[m].log;e(" Received: "+l);var w;if(w=!t())null===g.iframe?(x(" IFrame ("+g.id+") not found"),w=!1):w=!0;if(w&&n()){switch(g.type){case "close":a(g.iframe);break;case "message":u(l.substr(l.indexOf(":")+
7+6));break;case "scrollTo":r(!1);break;case "scrollToOffset":r(!0);break;case "inPageLink":v(l.substr(l.indexOf(":")+7+9));break;case "reset":B(g);break;case "init":b();d[m].initCallback(g.iframe);break;default:b()}F=!1}}});t(window,"resize",function(){J(function(){for(var c in d)if("parent"===d[c].resizeFrom){var b=document.getElementById(c);n("Window resize","resize",b,c);d[c].minHeight=d[c].minHeightCallBack();k(b,c,"minHeight")}},66)});window.jQuery&&K(jQuery);window.requestAnimFrame=window.requestAnimFrame||
function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(c){window.setTimeout(c,1E3/60)}}();"function"===typeof define&&define.amd?define([],r):"object"===typeof module&&"object"===typeof module.exports?module.exports=r():window.iFrameResize=r()})();
